#!/bin/bash

export INPUT_TYPE=$1

build_css() {
  # Get a list of all the CSS files in the app/components directory
  CSS_FILES=$(find app/components/sailboat -name '*.tcss' ! -path '*/sailboat.tcss')
  npx postcss $CSS_FILES --dir app/components --base app/components --ext css
  # Build main CSS bundle
  npx postcss -o app/assets/styles/sailboat_components.css app/components/sailboat/sailboat.tcss
}

# Function to build the assets
build_js() {
  node esbuild.mjs
}

if [ "$INPUT_TYPE" = "css" ]; then
  echo "Building CSS assets..."
  build_css
elif [ "$INPUT_TYPE" = "js" ]; then
  echo "Building JS assets..."
  build_js
else
  echo "Building all assets..."
  build_css
fi
