source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.2.1"

rails_version = (ENV["RAILS_VERSION"] || "7.0.5").to_s

gem "rake", "~> 13.0"
gem "sprockets"
gem "sprockets-rails"

gem "actioncable", rails_version
gem "actionview", rails_version
gem "activemodel", rails_version
gem "activesupport", rails_version
gem "railties", rails_version

# Use Puma as the app server
gem "puma", "~> 6.3.0"

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", ">= 1.4.2", require: false

gem "sailboat_components", path: "../"
gem "view_component", ">= 3.2"
gem "lookbook", "~> 2.0.5"

group :development do
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem "spring", "~> 4.0"
  gem "spring-watcher-listen", "~> 2.1"
  gem "hotwire-livereload", "~> 1.1"
  # Use JavaScript with ESM import maps [https://github.com/rails/importmap-rails]
  gem "importmap-rails"

  # Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
  gem "turbo-rails"

  # Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
  gem "stimulus-rails"

  gem "foreman"

  gem "listen"
end
